on: [push]
jobs:
    build:
        runs-on: codeberg-tiny
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.26"
            - name: Build Client
              run: GOOS=js GOARCH=wasm go build -o static/ccwsui.wasm ./web
            - name: Build Server
              run: go build -o ./ccwsui-server .
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: ccwsui-server
                  path: ./ccwsui-server
